# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'CampusSelvagem' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CampusSelvagem

  target 'CampusSelvagemTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CampusSelvagemUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'CenteredCollectionView'
end

